# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaZNU2htzONVMGE0_WRg6K4WAHQNv4oQ
"""

import numpy as np

# Confusion matrix (rows = predicted, cols = gold)
conf_matrix = np.array([
    [5, 10, 5],   # Predicted Cat
    [15, 20, 10], # Predicted Dog
    [0, 15, 10]   # Predicted Rabbit
])

classes = ["Cat", "Dog", "Rabbit"]

# Per-class precision and recall
precisions = []
recalls = []

for i, cls in enumerate(classes):
    TP = conf_matrix[i, i]
    FP = conf_matrix[i, :].sum() - TP
    FN = conf_matrix[:, i].sum() - TP
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0
    precisions.append(precision)
    recalls.append(recall)
    print(f"{cls} -> Precision: {precision:.3f}, Recall: {recall:.3f}")

# Macro averages
macro_precision = np.mean(precisions)
macro_recall = np.mean(recalls)

# Micro averages
TP_total = np.trace(conf_matrix)
total_pred = conf_matrix.sum()
micro_precision = TP_total / total_pred
micro_recall = TP_total / total_pred

print(f"\nMacro Precision: {macro_precision:.3f}, Macro Recall: {macro_recall:.3f}")
print(f"Micro Precision: {micro_precision:.3f}, Micro Recall: {micro_recall:.3f}")