# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaZNU2htzONVMGE0_WRg6K4WAHQNv4oQ
"""

from collections import Counter

# Training corpus
corpus = [
    "<s> I love NLP </s>",
    "<s> I love deep learning </s>",
    "<s> deep learning is fun </s>",
]

def tok(s):
    return s.split()

# Unigram & bigram counts
unigrams = Counter()
bigrams = Counter()
context_totals = Counter()   # total next-words seen after a given token

for line in corpus:
    w = tok(line)
    unigrams.update(w)
    for i in range(len(w) - 1):
        prev_, cur = w[i], w[i+1]
        bigrams[(prev_, cur)] += 1
        context_totals[prev_] += 1

def bigram_mle(prev_, cur):
    """ P(cur | prev) by MLE """
    num = bigrams.get((prev_, cur), 0)
    den = context_totals.get(prev_, 0)
    return (num / den) if den > 0 else 0.0

def sentence_prob(sentence):
    """ Product of bigram MLEs over the sentence """
    w = tok(sentence)
    p = 1.0
    steps = []
    for i in range(len(w) - 1):
        prev_, cur = w[i], w[i+1]
        pc = bigram_mle(prev_, cur)
        steps.append((prev_, cur, pc))
        p *= pc
    return p, steps

# Test sentences
S1 = "<s> I love NLP </s>"
S2 = "<s> I love deep learning </s>"

p1, steps1 = sentence_prob(S1)
p2, steps2 = sentence_prob(S2)

# ---- Print results ----
print("=== Unigram Counts ===")
for w, c in sorted(unigrams.items()):
    print(f"{w:>10}: {c}")

print("\n=== Bigram Counts (prev -> next) ===")
for (a, b), c in sorted(bigrams.items()):
    print(f"{a:>10} -> {b:<10}: {c}")

print("\n=== S1 steps ===")
for a, b, pc in steps1:
    print(f"P({b} | {a}) = {pc:.4f}")
print(f"S1 Probability = {p1:.6f}")

print("\n=== S2 steps ===")
for a, b, pc in steps2:
    print(f"P({b} | {a}) = {pc:.4f}")
print(f"S2 Probability = {p2:.6f}")

print("\nPreferred:", "S1" if p1 > p2 else "S2" if p2 > p1 else "Tie")
if p1 != p2:
    print("Why:", "Higher product of bigram probabilities (MLE).")